### ISSUE TITLE
compiling for php help

### ISSUE THREAD

**Issue by phillrab2009** [SICOM/rlib#34]
Hi, I'm attempting to install rlib 2.0.20 on a fresh Ubuntu 18.04 install with PHP 7.2. We have a very VERY old OS running rlib 1.3.7 on a Fedora Core 5 server and it's far past time that it get some love.

I've gotten the package to compile and install, but it's not installing with PHP bindings from what I can tell. It does appear to attempt to include these by default. I'm saying this based off of reading through the configure file. It would appear that "enable_php" flag is present without any additional arguments during the configure run. Also, it appears to be searching for "php-config", but I'm not seeing this file, or a way to generate it. Is there a current how-to or guide that I can reference? I'm not seeing anything included with the source...

It would appear from some internet digging that since SICOM was acquired by Xenial, and it doesn't look like Xenial has any references to documentation or support for rlib. I'm kind of assuming that they're burying rlib...

Any help or advice is much appreciated.

**Comment by hunandrew** [comment]
@phillrab2009  I hope it can help you a little bit: [https://web.archive.org/web/20131116192443/http://newrlib.sicom.com/~rlib/index.php/Documentation](url)

**Comment by zboszor** [comment]
Sicom will not develop RLIB anymore, the Xenial acquisition did not bring over the RLIB documentation. Thanks for the webarchive link.

FYI, there's an unreleased version 2.0.21:
https://github.com/SICOM/rlib/commits/rlib-2.0.21-RLIB-22-GCC-6-fix
It brings back support for PHP 7.x that 2.0.20 doesn't have after 2.0.18 reverted  a lot of incremental changes to 2.0.9.

However, we carry other changes in that  2.0.21 branch, like switching the PDF output generator to use libharu 2.3.0 from https://github.com/libharu/libharu/releases because it handles embedded fonts that our internal RPDF library didn't do and also handles certain PNG quirks that our code didn't handle. If you don't want to deal with the extra libharu dependency, you may be better off with RLIB 2.0.17 that supports PHP 7.x.

I also have a work-in-progress rewrite of RLIB from scratch at https://github.com/zboszor/OpenCReports that I am slowly progressing with but don't hold your breath for it. At this time, only the expression parser was implemented based on Flex/Bison instead of the fragile custom parser in RLIB. All drawing and the PDF output will eventually use Cairo, mostly because libharu seems to be dead with no maintainer, although there are useful PRs extending/fixing it.

**Comment by phillrab2009** [comment]
Thank you both! 
@hunandrew, I had been trying to reference that web archive link on Friday. A lot of it seemed purely aimed at a windows implementation and I was wondering if I was missing something in my translation. 
@zboszor, Thank you for that insight! I remember having read over release notes for 2.0.18 about the  reversion of features to 2.0.9, BUT much to my personal learning curve I did not realize support for php7.x was still absent from 2.0.20. I will attempt an install with 2.0.17 first given the info you've provided here and report back.

**Comment by zboszor** [comment]
@phillrab2009 Maybe we should have been clearer when writing the documentation, but the first two sentences of https://web.archive.org/web/20130529171655/http://newrlib.sicom.com/~rlib/index.php/Documentation_Install should tell the basics:

> RLIB uses the autoconf framework for detecting dependencies. This is not a native Windows development environment, so compilation from source needs substantial preparation before compilation can be attempted.

So:
```
$ autoreconf -vif -Wall
$ ./configure --prefix=/usr (and any other necessary options)
$ make
$ sudo make install
```

**Comment by phillrab2009** [comment]
@zboszor Thank you again, I've been using the autogen.sh script but missed the Autoreconf portion. I might have to give the libharu route a try though because upon "make" (after successful "configure" +flags ) I'm getting an error for rpdf.c. "-Werror=implicit-fallthrough="

Here's my current commands leading up to the error - 
`$ autoreconf -vif -Wall
$ ./configure --prefix=/usr --disable-postgres --enable-php
$ make`

here's the error output portion - 
`rpdf.c: In function ‘rpdf_image’:
rpdf.c:1320:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
      loop = FALSE;
rpdf.c:1321:8: note: here
        default:
        ^~~~~~~
cc1: all warnings being treated as errors
Makefile:518: recipe for target 'rpdf.lo' failed
make[2]: *** [rpdf.lo] Error 1`

in looking at the rpdf.c at line 1320 this appears related to reaching "case M_SOS". I'm still trying to figure out what is triggering that.

**Comment by phillrab2009** [comment]
Oh and here's the output of configure (minus the postcard bit) -
```
rlib-2.0.17:

   prefix:                   /usr
   compiler:                 gcc
   UTF8 enabled:             yes
   WIN32 build:              no
   Documentation:            no

   INPUTS:
    MYSQL:                   yes built-in: no
    POSTGRES:                no built-in: no
    ODBC:                    no built-in: no

   COMPRESSION:
    PDF:                     yes

   GRAPHING:
    PDF:                     Always
    HTML:                    no

   BINDINGS:
    PHP:                     yes
      PHP version:           7.2.19-0ubuntu0.18.04.2
      PHP ini directory:     /etc/php/7.2/cli/conf.d
    PYTHON:                  yes
     PYTHON version:         2.7
     PYTHON script dir:      ${prefix}/lib/python2.7/dist-packages
     PYTHON entension dir:   ${exec_prefix}/lib/python2.7/dist-packages
     PYTHON module dir:      ${pyexecdir}/rlib
    JAVA:                    no
    CSHARP:                  no
    PERL:                    yes
     PERL entension dir:     /usr/lib/x86_64-linux-gnu/perl/5.26
```

**Comment by zboszor** [comment]
GCC 9 does fail to build 2.0.17 at that point, CLang 9 doesn't but it throws on an error elsewhere on the code. Both are code bugs in 2.0.17. You can try removing occurrences of `-Werror` from `configure.ac` and re-run from autoreconf.

**Comment by phillrab2009** [comment]
Sweet. Between removing all ```-Werror``` occurences from ```configure.ac``` and installing ```libgd-dev``` which I was apparently missing I got it to install! Now I'm onto fighting through the older report script and dealing with some differences between 1.3.7 and 2.0.17. Thank you!!
